// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once
#define NO_ACTION_ONESHOT
#define MIDI_BASIC

#undef RGBLIGHT_EFFECT_CHRISTMAS
#undef RGBLIGHT_EFFECT_TWINKLE

#undef ENABLE_RGB_MATRIX_PIXEL_RAIN
#undef ENABLE_RGB_MATRIX_PIXEL_FLOW
#undef ENABLE_RGB_MATRIX_PIXEL_FRACTAL

#undef PRODUCT_ID
#define PRODUCT_ID 0xCCD1

#define DYNAMIC_KEYMAP_LAYER_COUNT 5
