stages:
  - test

QMK Firmware:
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - linux
  image: qmkfm/qmk_cli
  before_script:
    - python3 -m pip install -r requirements-dev.txt
    - avr-gcc --version
    - uname -a
  script:
    - make planck/rev6:default planck/rev5:default
    - make all:drashna -j2
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - ./*.hex
      - ./*.bin
      - ./*.uf2
    expire_in: 1 month
