#pragma once

/* Double tap reset button to enter bootloader */
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP13
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 750U


#define SPI_DRIVER SPID1
#define SPI_MISO_PIN GP8
#define SPI_MOSI_PIN GP15
#define SPI_SCK_PIN  GP14

#define DISPLAY_CS_PIN GP25
#define DISPLAY_DC_PIN GP29
#define DISPLAY_RST_PIN GP24

#define BACKLIGHT_PWM_DRIVER PWMD6
#define BACKLIGHT_PWM_CHANNEL RP2040_PWM_CHANNEL_A
// #define BACKLIGHT_PIN GP28
// #define BACKLIGHT_LEVELS 5

// #define WS2812_DI_PIN GP21
// #define WS2812_PIO_USE_PIO1
// #define RGBLIGHT_LED_COUNT 1
